---
abstract: 'lightweight form validation library'
author:
  - 'Tokuhiro Matsuno <tokuhirom {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Requires: 0.03
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FormValidator-Lite
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Email::Valid::Loose: 0
requires:
  Filter::Util::Call: 0
  Scalar::Util: 1.19
  UNIVERSAL::require: 0.11
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
